In [10]:
import numpy as np 
A = np.ones((2, 3))
B = 3
print(A+B) # résultat 1



[[4. 4. 4.]
 [4. 4. 4.]]


In [8]:

C = np.ones((2, 3))
D = np.ones((2, 1)) # D a une colonne, elle sera étendu sur les trois colonnes de C
print(C+D) # résultat 2

[[2. 2. 2.]
 [2. 2. 2.]]


In [16]:

C = np.ones((3, 2))
D = np.ones((1, 2)) 
print(C+D) # résultat 2

[[2. 2.]
 [2. 2.]
 [2. 2.]]
