In [7]:
import numpy as np
A = np.array ([[1,2,3],[4,5,6]])
A

print (A.sum())
print (A.mean(axis=0))

21
[2.5 3.5 4.5]


In [19]:
B = np.random.randint( 0 , 10, [5 ,5])
print(B)
print(B.argsort())  # retourner les indexs pour trier chaque ligne du tableau 
print (B [ : , 0].argsort()) # retourne les indices pour trier la 1 ere colonne de B 


[[2 4 4 0 7]
 [8 3 5 8 6]
 [2 8 5 2 2]
 [6 0 7 5 4]
 [1 9 0 5 6]]
[[3 0 1 2 4]
 [1 2 4 0 3]
 [0 3 4 2 1]
 [1 4 3 0 2]
 [2 0 3 4 1]]
[4 0 2 3 1]


In [37]:
# STATISTIQUES 
np.random.seed(0)
A = np.random.randint(0, 10, [5,5])
print(A)
print(np.unique(A, return_index= True, return_counts = True )) 

[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]
 [6 7 7 8 1]
 [5 9 8 9 4]]
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 1, 14,  8,  2,  9,  0, 11,  4, 12,  5], dtype=int64), array([1, 2, 1, 3, 2, 3, 2, 4, 4, 3], dtype=int64))
